### ISSUE TITLE
SLATE CLI does not always time out when it should

### ISSUE THREAD

**Issue by jmcragun** [slateci/slate-client-server#105]
@emersonford Pointed out that there are cases when setting up clusters/applications in which if some part(s) of the setup hangs, SLATE will not timeout. Changes should be made to ensure that it does. More details can/should be added as more specifics are brought to light.

**Comment by Mansalu** [comment]
For clarification, this is specific to the Cluster Registration process.

**Comment by Mansalu** [comment]
It seems unadvised to make this change, there may still be situations which this particular timeout could be harmful.
