### ISSUE TITLE
Cluster deletion silently deletes instances, secrets

### ISSUE THREAD

**Issue by cnweaver** [slateci/slate-client-server#11]
If the VO owning a cluster deletes itself or the cluster we must delete any other VOs' application instances and secrets from it. However, this could potentially surprise those other VOs, who might expect their applications to continue running. Notifying them might depends on having an overall VO contact, in order to avoid spamming all VO members.

**Comment by cnweaver** [comment]
Depends on #1

**Comment by manglano** [comment]
#1 merged so I'll just jump in here
