### ISSUE TITLE
Split `slate instance info` into separate file descriptors

### ISSUE THREAD

**Issue by LincolnBryant** [slateci/slate-client-server#112]
Currently the output of an instance looks like this:

```
Name                  Started                         App Version Chart Version           Group Cluster       ID
foo                        jan-1-1970                    1                    2                   blah       instance_foo

Services: (none)

Pods:
   podname
   Status: Running
   some other fun info:
      and more here here

Configuration:
  blahblahblah
```

I suggest we output configuration into a separate file descriptor.

A common workflow for me is as follows:

```
slate instance info > somefile.yaml
# copy and paste config at the end into a new file, make my changes
slate app install newapp --conf config.yaml
```

I would like, instead, to be able to do  something like:

```
slate instance info 2> config.yaml
vim config.yaml # make my changes only to the config
slate app install newapp --conf config.yaml
```

This would be a bit more composable, I think. 

What do you guys think?

**Comment by cnweaver** [comment]
The other option, which I think we've discussed before, would be to have a separate command or mode which outputs only the config. What about:

	$ slate instance info --config-only instance_123456 > config.yaml
	$ vim config.yaml # make my changes only to the config
	$ slate app install newapp --conf config.yaml

(Ab)using stderr for this just feels a bit funny to me for data which is not related to or produced by any sort of error. On the other hand, one could choose to just view fds 1 and 2 as two separate communication channels to the shell, through which any data could be sent.

**Comment by LincolnBryant** [comment]
Yes indeed. I also am not entirely comfortable with stderr for this purpose. Another flag is OK too.

Would be interested in hearing feedback from others as well. I don't want to prescribe a particular way to accomplish this.

**Comment by jmcragun** [comment]
Personally, as someone who's looking into implementing this now, I definitely prefer the idea of using (a) flag(s) to specify what kind of output we want from various requests. For simplicity (and arguably consistency) I'm leaning on having the syntax look like
```
$ slate instance info --conf instance_123456 > config.yaml
$ ...
```
Assuming nobody else has qualms about doing things that way. This also might involve making some changes to our request schema, I'm guessing

**Comment by LincolnBryant** [comment]
Sounds great- let's do it!
