### ISSUE TITLE
`--output json` interacts poorly with complex output formats

### ISSUE THREAD

**Issue by cnweaver** [slateci/slate-client-server#12]
This affects `instance info` and `secret info` in particular, giving a mix of JSON and non-JSON output.

**Comment by manglano** [comment]
Ah, this is a bit simpler than I thought it was yesterday

**Comment by cnweaver** [comment]
Correct, I think that's the crux of it. Also, the output formats divide roughly into the tabular/human ones and JSON-based ones, so it's not just the JSON output alone which is affected, but all outputs of that general type, including jsonpointer and jsonpointer-file.

**Comment by manglano** [comment]
Closed by #25.
