### ISSUE TITLE
add option to list storage classes by cluster

### ISSUE THREAD

**Issue by jstidd** [slateci/slate-client-server#122]
It would be nice to have a list of storage classes by cluster in the API, Client, and available for the portal to pull from through AJAX. I opened an issue for the portal to include this information in the create volumes form (issue 101 in the portal repo)

**Comment by jmcragun** [comment]
For documentation purposes: After discussing this ticket in a regular meeting we came to the conclusion that the effort needed due to its complexity to implement would outweigh the benefits it would provide
