### ISSUE TITLE
Deleting nonexistent clusters fails

### ISSUE THREAD

**Issue by ike091** [slateci/slate-client-server#124]
SLATE seems to have trouble deleting clusters that no longer exist. I spun up a SLATE cluster on Cloudlab, which after some time naturally expired. However, SLATE still believes this cluster exists, and cannot delete it. When `slate cluster delete <cluster_id>` or `slate cluster delete --force <cluster_id>` is run, slate returns this output: `slate: Exception: curl perform DELETE failed` `curl error: Empty reply from server`.

**Comment by Mansalu** [comment]
I think there are two distinct things going on here:

1) The cluster deletion might actually just be timing out? Can you check to see if the cluster was eventually deleted by that request?

2) Volume force deletion needs to be updated to actually force delete if the cluster is unreachable

**Comment by ike091** [comment]
I checked a while later, and the cluster still failed to delete, so it's probably not just timing out.

**Comment by jstidd** [comment]
Deleting clusters with false seems to be working okay, could not recreate. However, there are still some timeout issues with nginx. When bypassing nginx it appears to work fine. Closing.
