### ISSUE TITLE
SLATE fails to delete volumes on nonexistent clusters

### ISSUE THREAD

**Issue by ike091** [slateci/slate-client-server#125]
SLATE seems to not be able to delete volumes on clusters that have been torn down by means other than SLATE (in my case, a cluster in Cloudlab that has expired). When `slate volume delete <volume_id>` or `slate volume delete --force <volume_id>` is run, slate returns this output: `slate: Exception: curl perform DELETE failed` `curl error: Empty reply from server.`

**Comment by jstidd** [comment]
I've done testing currently the Volumes are deleted from DynamoDB when a deleting a cluster from SLATE that is no longer available. Closing the ticket.
