### ISSUE TITLE
Alert the end user when a cert is imminently expiring

### ISSUE THREAD

**Issue by LincolnBryant** [slateci/slate-client-server#139]
It would be very nice if the SLATE API can do an optional check for remote cluster certificate expiry time when commands are run, such that the end user is alerted when a cluster is about to have a failed certificate. 

e.g.:
```
$ slate instance info instance_63YmqffFrJU
Name               Started                         App Version Chart Version            Group       Cluster       ID
osg-frontier-squid 2021-Jun-09 17:44:29.741715 UTC 4.13-1.1    osg-frontier-squid-1.7.3 atlas-squid uchicago-prod instance_63YmqffFrJU
...
**WARNING: Cluster certificate will expire in 19 days!**
```

**Comment by sthapa** [comment]
@LincolnBryant  isn't this addressed by the cluster check cron job?

**Comment by sthapa** [comment]
Cron job covers most of this
