### ISSUE TITLE
Database statistics are not accurate

### ISSUE THREAD

**Issue by cnweaver** [slateci/slate-client-server#14]
Currently we are tracking queries performed, scans performed, and local cache hits. However, for cache hits we are recording the number of items successfully found in the cache, while for queries we are recording only one entry even for queries which result in many items returned. THis should probably be revised, following the details on https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/CapacityUnitCalculations.html to give a clearer picture of what resources we are really using. This can't be perfect, since in the cases of queries or scans which filter output Amazon charges according to the size of the dataset before filtering, which we cannot know, but we could get closer to correct answers.

**Comment by sthapa** [comment]
Won't fix
