### ISSUE TITLE
Create SLATE disaster recovery command

### ISSUE THREAD

**Issue by LincolnBryant** [slateci/slate-client-server#144]
We have a series of manual steps for recovering a SLATE cluster that are not easily automated.

Here's what happens if a Cluster has some K8S-related meltdown and needs to be registered in SLATE, assuming they want to keep all of the objects present on that cluster:
1. `slate cluster create`  with the same name. This will install all of the objects, **and then fail.**
2. `slate cluster update -r` will send the new kubeconfig to the API server
3. create some dummy applications in each of the group namespaces, as to coax SLATE / NRP controller into creating the namespaces
4. `slate instance restart` on each affected instance
5. `slate secret copy` from the affected cluster to a secondary cluster. Secondary cluster is not guaranteed to exist. 
6. `slate secret copy -f` back from a secondary cluster to the affected cluster

From discussions in the SLATE slack. Can we create a recovery command that approximately:
1. reinstalls all of the needed objects, CRDs, etc
2. sends new cluster config to the API
3. puts all of the secrets back in place
4. puts all of the volumes back in place
5. puts all of the instances back in place

@cnweaver notes that there is a skeleton of recovery code in the server source, covering approximately steps 3-5. He also notes:
> Some of the existing issues should just be fixed in the API server, like that instance restart should be able to create the namespace if it doesn't exist (to avoid the need to do a dummy install first) and there should be some mechanism, at least inside the API server even if not explicitly exposed to users to restore a secret from the API's master copy (to avoid the weird copy-to-other-cluster-and-copy-back dance).

**Comment by cnweaver** [comment]
The skeleton code is `verifyCluster` and `repairCluster` in ClusterCommands.cpp. The former apparently got to a point of being functional enough that it is already exposed in the API, but some more recent additions like volume support were not added to it when they went in. It basically computes a diff between what the PersistentSTore thinks the cluster should have, and what it actually has. `repairCluster` was then supposed to take that data structure and bring the cluster into line with expectations, but that code never got written.

**Comment by sthapa** [comment]
Closing since we probably don't have the effort to address this right now.
