### ISSUE TITLE
Expose current node resource usage

### ISSUE THREAD

**Issue by ike091** [slateci/slate-client-server#146]
Exposing the current compute usage of cluster nodes through the `slate cluster info` command would be a useful feature to have. This could possibly leverage `kubectl describe nodes`?

**Comment by jmcragun** [comment]
For reference, could you specify which compute usage statistics you would like displayed specifically?

**Comment by ike091** [comment]
RAM and CPU usage would be the most useful ones in my opinion. I believe @LincolnBryant was actually the one who requested this, and he had a specific use case in mind, so maybe check with him?

**Comment by sthapa** [comment]
Resolved in #437
