### ISSUE TITLE
Improve slate volume list

### ISSUE THREAD

**Issue by phjorgen** [slateci/slate-client-server#156]
SLATE should skip waiting for timeout on inaccessible volumes when running slate volume list, perhaps by running kubectl commands and checking first if it's accessible. Relevant section of code at `src/VolumeClaimCommands.cpp:L155`

Related to issue [#154](https://github.com/slateci/slate-client-server/issues/154)

**Comment by cnweaver** [comment]
Strictly speaking, I think it's not possible to skip the timeout, as one can't know ahead of time which clusters will be broken, but by running all queries concurrently the total time taken won't ever be much more than the timeout time for one cluster (or for the longest query if no clusters are broken).

**Comment by sthapa** [comment]
Don't have effort to implement/re-architect
