### ISSUE TITLE
Unable to delete unreachable clusters

### ISSUE THREAD

**Issue by jstidd** [slateci/slate-client-server#168]
We are unable to delete unreachable clusters. After bypassing nginx (due to timeout issues) we get back the following error: 

Failed to delete cluster cluster_Ymki9IQYm9I: Failed to delete cluster due to failure deleting instance: helm delete failed: Error: Kubernetes cluster unreachable: Get "https://63.239.135.118:6443/version?timeout=32s": dial tcp 63.239.135.118:6443: i/o timeout

**Comment by cnweaver** [comment]
Does this occur even with the `--force` option?

**Comment by jstidd** [comment]
No, the force option resolves the issue - we just forgot to use it.
