### ISSUE TITLE
Optimize how many threads the API server runs

### ISSUE THREAD

**Issue by cnweaver** [slateci/slate-client-server#17]
Currently we run a number of threads equal to the system 'hardware concurrency' (usually the number of logical CPUs), which is certainly the minimum we want. However, for many operations the API server is just idling, waiting for kubernetes or tiller to send back a response, so it might make sense to 'overcommit' on threads. Figuring this out probably requires benchmarking, with at least three machines: one to run a test kubernetes cluster, one to run the API server, and one to generate the test load on the API server. Possibly a fourth machine to run DynamoDB so it doesn't have to share resources with the API server.

**Comment by sthapa** [comment]
Closing since the current config works okay and we are seeing under 1 request per sec so we don't need to optimize at the moment.
