### ISSUE TITLE
slate app install failure scenario

### ISSUE THREAD

**Issue by fengpinghu** [slateci/slate-client-server#188]
slate app install returns successful with instance id.  But the instance is not actually created in the cluster. 
The slate app install process may need to either
1) add instance check 
or
2) indication that successful installation only means success of helm install.

What happened was when we tried to deploy the perfsonar checker app.  The cluster has a pod admission policy that denied the pod creation. In this case we observed the "slate app install"  command finished successfully but the instance is not actually created.

W0503 20:17:44.459151       1 dispatcher.go:142] rejected by webhook "validation.gatekeeper.sh": &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:"", RemainingItemCount:(*int64)(nil)}, Status:"Failure", Message:"admission webhook \"validation.gatekeeper.sh\" denied the request: [denied by psp-privileged-container] Privileged container is not allowed: perfsonar-testpoint, securityContext: {\"privileged\": true}", Reason:"[denied by psp-privileged-container] Privileged container is not allowed: perfsonar-testpoint, securityContext: {\"privileged\": true}", Details:(*v1.StatusDetails)(nil), Code:403}}

**Comment by sthapa** [comment]
The second option is probably the best way to fix this since there are multiple scenarios where the pod gets scheduled but never gets allocated. I'll add some code to address this.

**Comment by sthapa** [comment]
Don't have effort to complete, closing
