### ISSUE TITLE
Unable to parse kubeconfig as YAML

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/slate-client-server#270]
## Description

From Patrick McGuigan (on Slack General channel) and @jstidd, when trying to register a cluster with Staging:
```shell
...
...
Sending config to SLATE server...
Failed to create cluster swt2-cpb-dev: Unable to parse kubeconfig as YAML
```

[Patrick goes on](https://slateci.slack.com/archives/C6E4WFCHK/p1661162241575619?thread_ts=1660866646.668869&cid=C6E4WFCHK) to look through the logs and noted some nginx issues which may or may not be related.

## Steps to Reproduce

1. Set up a Kubernetes cluster
2. Download `v1.0.24` SLATE client on the master node
3. Grab the token for https://api.staging.slateci.io (currently `v1.0.25`)
4. Run `slate cluster register <args>`

**Comment by sthapa** [comment]
Is this with the mac or linux client?

**Comment by adamhgriffith-uofu** [comment]
@jstidd was performing the task on a Linux VM. Not sure what Patrick McGuigan was using.

As per our chat in Slack I will endeavor to bring the following closer to the desired yamlcpp 0.5.1.
```shell
$ podman run -it hub.opensciencegrid.org/slate/slate-client-alpine:1.0.0 sh
...
Storing signatures
/ # apk list yaml*
yaml-cpp-0.6.2-r2 x86_64 {yaml-cpp} (MIT)
yaml-dev-0.2.2-r1 x86_64 {yaml} (MIT)
yaml-0.2.2-r1 x86_64 {yaml} (MIT)
yaml-cpp-dev-0.6.2-r2 x86_64 {yaml-cpp} (MIT)
```

**Comment by sthapa** [comment]
This was fixed in https://github.com/slateci/slate-client-server/pull/284 .  The fix was to pass the necessary parameters in the json message and build the kubeconfig yaml on the server side rather than sending the full yaml config as a string in the json message and then trying to extract it.
