### ISSUE TITLE
Explore Software Bill of Materials (sbom)

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/slate-client-server#315]
From [CISA](https://www.cisa.gov/sbom): A “software bill of materials” (SBOM) has emerged as a key building block in software security and software supply chain risk management. A SBOM is a nested inventory, a list of ingredients that make up software components.  The SBOM work has advanced since 2018 as a collaborative community effort, driven by [National Telecommunications and Information Administration’s (NTIA) multistakeholder process](http://ntia.gov/SBOM).

Several tools of interest:
* [syft](https://github.com/anchore/syft/)
* [grype](https://github.com/anchore/grype/) - vulnerability scanner used in tandem with *syft*.

**Comment by sthapa** [comment]
Closing due to lack of effort
