### ISSUE TITLE
Improve dns checks

### ISSUE THREAD

**Issue by sthapa** [slateci/slate-client-server#318]
Right now we validate dns names by checking for characters, we should use the c++ regex to do the check instead.  The check  code is at [ClusterCommands.cpp line 441.](https://github.com/slateci/slate-client-server/blob/develop/src/ClusterCommands.cpp#L435) . We should look at other places in the code that should use regex after this (there's about 20-30 places where it would be useful).

**Comment by cnweaver** [comment]
In all of those locations, it was an intentional choice to avoid using the regex library, as it is unusably broken in g++/libstdc++ <=4.8.5. If you want to use it, you will need to increase the minimum compiler version to at least the GCC 5 series.
