### ISSUE TITLE
Delete instance enhancement - display app and cluster with confirmation to delete.

### ISSUE THREAD

**Issue by jstidd** [slateci/slate-client-server#38]
When deleting an instance from the SLATE CLI it would be great to get back the application name and cluster it is running on along with a confirmation that you want to delete it. When deleting an instance I feel nervous because I cannot see that I copied the right one before its gone.

**Comment by cnweaver** [comment]
Makes sense; we can have a `-y` flag for the current behavior in case anyone wants to script things. The same confirmation should probably be included for clusters, groups, and secrets.
