### ISSUE TITLE
Generate shell completion scripts for CLI

### ISSUE THREAD

**Issue by cnweaver** [slateci/slate-client-server#4]
We should definitely support bash, probably zsh (does this use the same mechanisms as bash?).

**Comment by cnweaver** [comment]
This mostly works for bash, but is not working correctly for zsh.

**Comment by 4e554c4c** [comment]
Hi, I've been working on this a bit.

I was able to get ZSH completions working just by changing the zshHeader  to use `bashcompinit` instead of the translation

If this works I can send a PR, im not sure if the translation to zsh completions is there for a reason.

**Comment by Mansalu** [comment]
Send a PR and request review on it.

**Comment by cnweaver** [comment]
I'm also not sure exactly why that system was used; as mentioned before I copied it from Helm since I knew very little about zsh. If a simpler way works, I'm all for it.

**Comment by 4e554c4c** [comment]
Assuming this is resolved by #58
