### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/slate-client-server#423]
This has occurred several times today where the following error appears in the logs and the pod is restarted.
```json
{
insertId: "rwr5fb2yp2pxikgf"
labels: {7}
logName: "projects/slate-280713/logs/stderr"
receiveTimestamp: "2023-01-24T17:28:06.870993789Z"
resource: {2}
severity: "ERROR"
textPayload: "/docker-entrypoint.sh: line 4:     6 Segmentation fault      (core dumped) slate-service --config /slate/conf/slate.conf"
timestamp: "2023-01-24T17:28:02.238109522Z"
}
```
For convenience, here is a [link to the Google Log Explorer and an error query](https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22slate-280713%22%0Aresource.labels.location%3D%22us-central1-c%22%0Aresource.labels.cluster_name%3D%22primus%22%0Aresource.labels.namespace_name%3D%22production%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Finstance%3D%22slate-api-prod%22%0Alabels.k8s-pod%2Fapp_kubernetes_io%2Fname%3D%22slate-api%22%20severity%3E%3DDEFAULT%0Aseverity%3DERROR;timeRange=2023-01-24T10:28:54.722Z%2F2023-01-24T17:28:54.722869Z;cursorTimestamp=2023-01-24T17:28:02.238109522Z?project=slate-280713) highlighting this and related entries.

**Comment by adamhgriffith-uofu** [comment]
This isn't terribly informative but here are the logs from another segmentation fault today at 10:08 Mountain Time.
```
2023-02-16 10:08:02.992 MST
INFO: [2023-Feb-16 17:08:02.992195 UTC] (TID 140105691510336) Querying for cluster_iqLa5Ov8oZE
2023-02-16 10:08:02.992 MST
INFO: [2023-Feb-16 17:08:02.992231 UTC] (TID 140105691510336) Found cluster_iqLa5Ov8oZE
2023-02-16 10:08:02.995 MST
INFO: [2023-Feb-16 17:08:02.934529 UTC] (TID 140105699903040) user_zKfSKAc3maY (WebPortal) requested to ping cluster cluster_mvO9QzLUj94 from 35.191.10.72:59455
2023-02-16 10:08:03.003 MST
INFO: [2023-Feb-16 17:08:02.999802 UTC] (TID 140105699903040) Querying for cluster_mvO9QzLUj94
2023-02-16 10:08:04.985 MST
/docker-entrypoint.sh: line 4: 7 Segmentation fault (core dumped) slate-service --config /slate/conf/slate.conf
```

**Comment by robrwg** [comment]
Is docker-entrypoint.sh well understood?  Needed?

**Comment by adamhgriffith-uofu** [comment]
@robrwg, the entrypoint script is what the container runs, namely:
```
slate-service --config /slate/conf/slate.conf
```
The error is letting us know that `slate-server` is the process that is crashing.
