### ISSUE TITLE
Cluster information for unavailable cluster timing out

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/slate-client-server#434]
From @stidd on Slack:
> I am not sure who is handling the portal right now, but getting cluster information for unavailable clusters is timing out. It supposed to still show group and contact information

<img width="746" alt="Screenshot 2023-02-15 at 10 33 01 AM" src="https://user-images.githubusercontent.com/94396076/219135622-2e71f199-7231-4f03-9ebb-84fb86997ca7.png">

**Comment by adamhgriffith-uofu** [comment]
@sthapa mentioned during today's working session that this is an API bug. Issue has been updated and transferred.

**Comment by gcarcassi** [comment]
I've implemented a preliminary solution that does not require changes in the API service. First, it checks whether the cluster is unreachable. If it is, then get limited information about the cluster from the cluster list and skip storage and priority classes.
