### ISSUE TITLE
slate client fails to build on Boost >1.70

### ISSUE THREAD

**Issue by 4e554c4c** [slateci/slate-client-server#66]
Due to a bug in crow, see ipkn/crow#340
Could either apply manual patches or switch to one of the forks of crow.
There seem to be several fixes keeping compatability with boost <1.65 if that is necessary.

**Comment by cnweaver** [comment]
I have applied the https://github.com/moneroexamples/onion-monero-blockchain-explorer/commit/76a0efa8ee3ea5bb466b81d84357d2fd76920cbd fix for this, but do not have boost 1.70 handy on any system at the moment to test with, so I am only certain that it continues to work with older versions.

**Comment by 4e554c4c** [comment]
fixed by 1a3fa36
