### ISSUE TITLE
Implement certificate issuing with LE DNS challenges

### ISSUE THREAD

**Issue by cnweaver** [slateci/slate-client-server#72]
Services can currently have something of a chicken-and-egg problem for using HTTPS that they can't run until they have a cert, but can't answer LE challenges to get a cert until they are running. (Services using ingress are particularly affected.) This cycle can be broken if the SLATE API server is taught to examine values files for hostnames to be used with a certificate (to be identified in some yet-to-be-determined manner), and if the name is on a SLATE controlled domain make the request to Let's Encrypt and answer the challenge by creating a suitable DNS record, then injecting the resulting cert into a SLATE secret (whose is name correspondingly specified in the values file) for the application to use. The secret can then also outlive the application instance and be reused when the instance is restarted or reconfigured. This can also alleviate problems with repeatedly requesting the same cert from LE (which can lead to being blocked temporarily). 

Additional concern: Certificates thus issued must be renewed. SLATE should somehow handle this automatically.

**Comment by sthapa** [comment]
Dropping this for now.  With the GKE env, certificates get created by the GKE env / loadbalancer.
