### ISSUE TITLE
Poll ingress controller to check for IP

### ISSUE THREAD

**Issue by LincolnBryant** [slateci/slate-client-server#94]
While deploying SLATE on GKE, it took a considerably longer time than usual for our Ingress Controller to be assigned a public IP address from Google's special sauce load balancer. I.e., this step immediately failed:

```
Do you want to install the ingress controller now? [y]/n: y
slate: Exception: Ingress controller service has not received an IP address
```

(aside: SLATE was successful after re-running the command) 

I think we need to poll the ingress controller to see if it has an IP, as we do with other components during setup.

**Comment by cnweaver** [comment]
In a test on GKE, a new LoadBalancer service received an address after 36 seconds. Polling for up to two minutes seems like a safe place to start, then.
